# Generated by Django 3.0.7 on 2022-03-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='products',
            new_name='product',
        ),
    ]
